'use strict';
const {catalog,labels,tiers,maxed,games,money,price,fps,motherboard}=Vertex;
const prefix=document.body.dataset.prefix;
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const menu=$('#menuToggle'),links=$('#navLinks');
function closeMenu(){links.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');}
menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
links.addEventListener('click',closeMenu);
const partName=(p,k)=>k==='motherboard'?motherboard(p):catalog[k][p[k]][0];
const specList=p=>Object.keys(catalog).map(k=>`<div><dt>${labels[k]}</dt><dd>${esc(partName(p,k))}</dd></div>`).join('');
const note='Illustrative planning estimates, not verified benchmarks. Settings, drivers, and game versions affect results.';
const fpsText=(p,res,g)=>{const f=fps(p,res,g);return f?`${f.join('–')} FPS`:'Not estimated';};
function table(p,res){return `<div class="table-scroll"><table class="perf-table"><thead><tr><th scope="col">Game</th><th scope="col">${res} estimate</th></tr></thead><tbody>${Object.keys(games).slice(0,4).map(g=>`<tr><td>${g}</td><td>${fpsText(p,res,g)}</td></tr>`).join('')}</tbody></table></div><p class="perf-note">${note}</p>`;}
if($('#systemCards')){
 $('#systemCards').innerHTML=Object.entries(tiers).map(([id,t])=>`<article class="sys-card ${id==='max'?'max-card':''}" data-resolution="${t.resolution}"><div class="tag">${id==='max'?'Flagship · ':''}${t.resolution} gaming</div><img class="system-image" src="assets/system.svg" width="600" height="500" alt="Illustration of a Vertex ${t.name} gaming tower" loading="lazy"><h3>Vertex ${t.name}</h3><p class="card-description">${{core:'Your first step. A serious upgrade.',pro:'The sweet spot for your next session.',ultra:'For players who push further.',max:'Your ambition. Without compromise.'}[id]}</p><ul><li>${esc(catalog.cpu[t.parts.cpu][0])}</li><li>${esc(catalog.gpu[t.parts.gpu][0])}</li><li>${esc(catalog.memory[t.parts.memory][0])}</li><li>${esc(catalog.storage[t.parts.storage][0])}</li></ul><p class="starting">Starting estimate <strong>${money(price(t.parts))}</strong>${id==='max'?`Upgrades to ~${money(price(maxed))}`:''}</p><p class="hint">1-year limited parts &amp; labor warranty</p><a class="btn ${id==='max'?'btn-primary':'btn-outline'}" href="gaming-pcs/${id}.html">Explore ${t.name} →</a></article>`).join('');
 document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});document.querySelectorAll('[data-resolution]').forEach(c=>c.hidden=b.dataset.filter!=='all'&&c.dataset.resolution!==b.dataset.filter);}));
}
if($('#performanceTable'))$('#performanceTable').innerHTML=`<div class="table-scroll"><table class="perf-table"><thead><tr><th>Game</th><th>1080p</th><th>1440p</th><th>4K</th></tr></thead><tbody>${Object.entries(games).slice(0,4).map(([g,v])=>`<tr><td>${g}</td>${v.map(n=>`<td>${n} FPS</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="perf-note">Original reference Ultra figures. ${note} New configurations are scaled from this reference.</p>`;
if($('#product')){const t=tiers[$('#product').dataset.tier],id=$('#product').dataset.tier;
 $('#product').innerHTML=`<div class="product-layout"><figure class="product-visual"><img src="../assets/system.svg" width="600" height="500" alt="Illustration of a Vertex ${t.name} gaming tower"><figcaption>Concept illustration. Explore the live 3D view in the configurator.</figcaption></figure><div><div class="eyebrow">${t.resolution} gaming, your way</div><h1>Vertex ${t.name}</h1><p class="product-copy">${{core:'A confident start for esports, everyday play, and your first custom setup.',pro:'Smooth high-resolution play with room to grow. Built for your everyday escape.',ultra:'A powerful starting point for immersive worlds and ambitious setups.',max:'Our flagship for immersive 4K gaming, demanding creative work, and an uncompromising setup. Start around $4,000 and personalize your build up to roughly $8,000.'}[id]}</p><p class="starting">Starting estimate <strong>${money(price(t.parts))}</strong></p><a class="btn btn-primary" href="../custom-build.html?base=${id}">Configure System in 3D →</a><p class="hint">Historical catalog prices and planning allowances. Final pricing and availability require confirmation.</p><a class="warranty-link" href="../warranty.html">1-year limited parts &amp; labor warranty →</a></div></div><div class="support-grid"><div class="panel"><h2>Inside the system</h2><dl class="spec-list">${specList(t.parts)}</dl></div><div class="panel"><h2>Estimated performance</h2>${table(t.parts,t.resolution)}<h3>Make room for more.</h3><p>Explore AMD or Intel processors, multiple graphics brands, and DDR5 memory kits. Personalize storage, cooling, case style, and lighting with a live 3D preview.</p><h3>One year of confidence.</h3><p>Supplied parts and assembly defects are covered for one year from delivery under our limited warranty. <a class="inline-link" href="../warranty.html">Read coverage, exclusions, and claim instructions →</a></p></div></div>`;
}
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
if($('#supportForm')){if(new URLSearchParams(location.search).get('topic')==='warranty')$('#topic').value='Warranty question';$('#supportForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);download('vertex-support-request.txt',Array.from(d,([k,v])=>`${k}: ${v}`).join('\n\n'));$('#supportStatus').textContent='Request prepared and download started. Nothing has been sent.';});}
if($('#components')){
 let base=new URLSearchParams(location.search).get('base');if(!Object.hasOwn(tiers,base))base='core';
 let tier=base,parts={...tiers[base].parts},selected=new Set(['Call of Duty','Fortnite']),customized=false;
 $('#tierPresets').innerHTML=Object.entries(tiers).map(([id,t])=>`<button class="filter" data-preset="${id}" aria-pressed="false">${t.name} <span>${money(price(t.parts))}</span></button>`).join('')+'<button class="filter" data-preset="maxed" aria-pressed="false">MAX expanded <span>'+money(price(maxed))+'</span></button>';
 function preset(id){tier=id==='maxed'?'max':id;parts={...(id==='maxed'?maxed:tiers[id].parts)};customized=id==='maxed';['resolution','goal','budget'].forEach(k=>$('#'+k).value=id==='maxed'&&k==='budget'?8000:tiers[tier][k]);renderComponents();render();}
 $('#tierPresets').addEventListener('click',e=>{const b=e.target.closest('[data-preset]');if(b)preset(b.dataset.preset);});
 ['resolution','goal','budget'].forEach(k=>{$('#'+k).value=tiers[base][k];$('#'+k).addEventListener('change',recommend);});
 $('#gameChoices').innerHTML=Object.keys(games).map(g=>`<label class="game-choice"><input type="checkbox" value="${g}" ${selected.has(g)?'checked':''}>${g}</label>`).join('');
 $('#gameChoices').addEventListener('change',e=>{e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);render();});
 function recommend(){const r=['1080p','1440p','4K'].indexOf($('#resolution').value),goal=+$('#goal').value,budget=+$('#budget').value;const desired=Math.min(3,r+(goal>=144?1:0)+(goal>=240?1:0));const affordable=Object.values(tiers).reduce((best,t,i)=>price(t.parts)<=(budget===1000?999:budget)?i:best,0);tier=Object.keys(tiers)[Math.min(desired,affordable)];parts={...tiers[tier].parts};customized=false;renderComponents();render();}
 function options(k){const groups=new Map();catalog[k].forEach(([name,cost,meta],i)=>{const brand=meta.brand||'';if(!groups.has(brand))groups.set(brand,[]);groups.get(brand).push(`<option value="${i}" ${parts[k]===i?'selected':''}>${esc(name)} · ${money(cost)}</option>`);});return [...groups].map(([brand,opts])=>brand?`<optgroup label="${esc(brand)}">${opts.join('')}</optgroup>`:opts.join('')).join('');}
 function renderComponents(){ $('#components').innerHTML=Object.keys(catalog).map(k=>`<div class="${['cpu','gpu','memory','motherboard'].includes(k)?'full':''}"><label for="part-${k}">${labels[k]}</label><select id="part-${k}" data-part="${k}" aria-describedby="detail-${k}">${options(k)}</select><p class="part-detail" id="detail-${k}"></p></div>`).join('');}
 $('#components').addEventListener('change',e=>{parts[e.target.dataset.part]=+e.target.value;customized=true;render();});
 function performance(){return selected.size?`<ul class="fps-list">${[...selected].map(g=>`<li><span>${g}</span><strong>${fpsText(parts,$('#resolution').value,g)}</strong></li>`).join('')}</ul>`:'<p class="hint">Select games to see performance estimates.</p>';}
 function render(){const total=price(parts),budget=+$('#budget').value,errors=Vertex.issues(parts);$('#recommendation').textContent=`Vertex ${tiers[tier].name} ${customized?'custom configuration':'starting point'}. Customize any component below.`;
 const miss=[...selected].some(g=>{const f=fps(parts,$('#resolution').value,g);return f&&f[1]<+$('#goal').value;});
 $('#liveSummary').innerHTML=`<p class="price">${money(total)} <small>USD planning estimate</small></p><p class="hint">Includes ${money(catalog.motherboard[parts.motherboard][1])} for the motherboard and assembly. Tax and shipping excluded.</p><p class="budget-status">${(budget===1000?total>=budget:total>budget)?'Outside your selected budget. Adjust components or your budget.':'Within your selected budget ceiling.'}</p><dl class="mini-specs"><div><dt>Processor</dt><dd>${esc(catalog.cpu[parts.cpu][0])}</dd></div><div><dt>Graphics</dt><dd>${esc(catalog.gpu[parts.gpu][0])}</dd></div><div><dt>Platform</dt><dd>${esc(motherboard(parts))}</dd></div></dl><h3>Estimated FPS · ${$('#resolution').value}</h3>${performance()}${miss?'<p class="notice">Some selected games may fall short of your FPS goal. Consider a higher graphics tier or lower resolution.</p>':''}<div id="compatibilityStatus">${errors.length?errors.map(x=>`<p class="notice">${esc(x)}</p>`).join(''):'<p class="compatibility-ok">✓ Preliminary component checks passed.</p>'}</div><p class="hint">${note}</p>`;$('#reviewBuild').disabled=!!errors.length;
 Object.keys(catalog).forEach(k=>{const meta=catalog[k][parts[k]][2];let detail=k==='motherboard'?motherboard(parts):k==='cpu'?`${meta.socket} · ${meta.source.core_count} cores`:k==='gpu'?`${meta.length}mm card · ${meta.minPsu}W minimum configuration rule`:k==='memory'?`${meta.sticks} sticks · ${meta.capacity}GB total · Final speed depends on the CPU and motherboard`:'';$('#detail-'+k).textContent=detail;});
 document.querySelectorAll('[data-preset]').forEach(b=>{const presetParts=b.dataset.preset==='maxed'?maxed:tiers[b.dataset.preset].parts;const same=Object.keys(catalog).every(k=>parts[k]===presetParts[k]);b.classList.toggle('active',same);b.setAttribute('aria-pressed',same);});
 window.vertexBuild={...parts};document.dispatchEvent(new CustomEvent('vertex:build-change',{detail:{...parts}}));
 }
 $('#resetBuild').addEventListener('click',recommend);
 $('#reviewBuild').addEventListener('click',()=>{if(Vertex.issues(parts).length)return;$('#reviewTitle').textContent='Review your build';$('#reviewContent').innerHTML=`<p class="price">${money(price(parts))}</p><p>${$('#resolution').value} · ${$('#goal').selectedOptions[0].text} target · ${$('#budget').selectedOptions[0].text} budget</p><dl class="spec-list">${specList(parts)}</dl><h3>Your games</h3>${performance()}<p class="hint">Historical catalog and planning estimate; tax and shipping excluded. Exact models and fit require final review. Confirmation stays in this browser and does not place an order.</p><p><a class="inline-link" href="warranty.html" target="_blank" rel="noopener">Includes a 1-year limited parts &amp; labor warranty ↗</a></p>`;$('#confirmBuild').hidden=false;$('#editBuild').textContent='Back to editing';$('#reviewDialog').showModal();});
 $('#editBuild').addEventListener('click',()=>$('#reviewDialog').close());
 $('#confirmBuild').addEventListener('click',()=>{$('#reviewTitle').textContent='Your build is ready.';$('#confirmBuild').hidden=true;$('#editBuild').textContent='Keep editing';const p=document.createElement('p');p.className='confirmation';p.textContent='Configuration confirmed locally. No order or payment has been submitted.';$('#reviewContent').prepend(p);const b=document.createElement('button');b.className='btn btn-primary';b.textContent='Download build summary';b.addEventListener('click',()=>download('vertex-build.txt',`Vertex Gaming — ${tiers[tier].name} build summary\n${$('#resolution').value} / ${$('#goal').value} FPS goal\nBudget: ${$('#budget').selectedOptions[0].text}\n\n${Object.keys(catalog).map(k=>`${labels[k]}: ${partName(parts,k)} (${money(catalog[k][parts[k]][1])})`).join('\n')}\nEstimate: ${money(price(parts))} USD, excluding tax/shipping\nGames: ${[...selected].join(', ')||'None selected'}\n\n${note}\nCPU/GPU/RAM catalog dated ${Vertex.source.sourceUpdated}; not live prices or stock.\n1-year limited parts and labor warranty; see warranty.html for coverage and exclusions.\nLocal configuration only. No order submitted.`));$('#reviewContent').append(b);});
 renderComponents();render();
}
