const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {spawn}=require('node:child_process');
const server=spawn('python3',['-m','http.server','8099','--bind','127.0.0.1'],{cwd:path.join(__dirname,'..'),stdio:'ignore'});
const base='http://127.0.0.1:8099/';
(async()=>{
 for(let i=0;i<40;i++){try{const r=await fetch(base);if(r.ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const chrome=process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
 const browser=await chromium.launch({...(fs.existsSync(chrome)?{executablePath:chrome}:{}),headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];page.on('pageerror',e=>errors.push(e.message));
 const paths=['index.html','gaming-pcs.html','gaming-pcs/core.html','gaming-pcs/pro.html','gaming-pcs/ultra.html','gaming-pcs/max.html','custom-build.html','services.html','about.html','support.html','warranty.html','catalog.html','vertex-gaming.html'];
 const visited=new Set();
 for(const file of paths){await page.goto(base+file);assert.equal(await page.locator('h1').count(),1,file);for(const url of await page.locator('a[href]').evaluateAll(as=>as.map(a=>a.href))){if(url.startsWith(base)&&!visited.has(url)){visited.add(url);assert((await page.request.get(url)).ok(),url);}}assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),file+' overflow');}
 await page.goto(base+'gaming-pcs.html');assert.equal(await page.locator('.sys-card').count(),4);await page.getByRole('button',{name:'4K',exact:true}).click();assert.equal(await page.locator('.sys-card:visible').count(),2);
 for(const tier of ['core','pro','ultra','max']){await page.goto(base+'custom-build.html?base='+tier);await page.waitForFunction(()=>document.querySelector('#buildViewport').dataset.modelRevision);assert.equal(await page.locator('#resolution').inputValue(),{core:'1080p',pro:'1440p',ultra:'4K',max:'4K'}[tier]);assert(await page.locator('#reviewBuild').isEnabled(),tier);}
 const v=await page.evaluate(()=>({count:[Vertex.catalog.cpu.length,Vertex.catalog.gpu.length,Vertex.catalog.memory.length],max:Vertex.price(Vertex.tiers.max.parts),expanded:Vertex.price(Vertex.maxed)}));assert.deepEqual(v.count,[16,18,10]);assert.equal(v.max,4000);assert.equal(v.expanded,7965);
 await page.locator('[data-preset=maxed]').click();assert((await page.locator('#liveSummary .price').textContent()).includes('7,965'));assert(await page.locator('#reviewBuild').isEnabled());
 let revision=+await page.locator('#buildViewport').getAttribute('data-model-revision');await page.locator('#part-memory').selectOption('1');await page.waitForFunction(n=>+document.querySelector('#buildViewport').dataset.modelRevision>n,revision);assert((await page.locator('#previewParts').textContent()).includes('2 RAM sticks'));
 await page.locator('#part-cpu').selectOption('15');assert((await page.locator('#detail-motherboard').textContent()).includes('LGA1851'));await page.locator('#part-cpu').selectOption('12');assert((await page.locator('#detail-motherboard').textContent()).includes('LGA1700'));
 await page.locator('#part-psu').selectOption('0');assert(await page.locator('#reviewBuild').isDisabled());await page.locator('#part-psu').selectOption('4');await page.locator('#part-case').selectOption('0');assert(await page.locator('#reviewBuild').isDisabled());await page.locator('#part-case').selectOption('3');await page.locator('#part-cooling').selectOption('0');assert(await page.locator('#reviewBuild').isDisabled());await page.locator('#part-cooling').selectOption('4');assert(await page.locator('#reviewBuild').isEnabled());
 await page.locator('[data-preset=maxed]').click();await page.locator('#part-cpu').selectOption('0');assert(await page.locator('#reviewBuild').isDisabled());await page.locator('#part-cpu').selectOption('8');await page.locator('#part-motherboard').selectOption('0');assert(await page.locator('#reviewBuild').isDisabled());await page.locator('[data-preset=maxed]').click();
 const camera=await page.locator('#buildViewport').getAttribute('data-camera');await page.locator('[data-view=side]').click();await page.waitForFunction(c=>document.querySelector('#buildViewport').dataset.camera!==c,camera);const side=await page.locator('#buildViewport').getAttribute('data-camera');await page.locator('#buildViewport canvas').focus();await page.keyboard.press('ArrowLeft');await page.waitForFunction(c=>document.querySelector('#buildViewport').dataset.camera!==c,side);
 const bb=await page.locator('#buildViewport canvas').boundingBox();await page.mouse.move(bb.x+bb.width/2,bb.y+bb.height/2);await page.mouse.down();await page.mouse.move(bb.x+bb.width/2+80,bb.y+bb.height/2+20,{steps:5});await page.mouse.up();
 await page.locator('#explodeView').click();assert.equal(await page.locator('#buildViewport').getAttribute('data-exploded'),'true');await page.locator('#glassView').click();assert.equal(await page.locator('#buildViewport').getAttribute('data-glass'),'false');
 await page.locator('#reviewBuild').click();assert(await page.locator('dialog').isVisible());assert((await page.locator('#reviewContent').textContent()).includes('X870E'));await page.locator('#confirmBuild').click();const d=page.waitForEvent('download');await page.getByRole('button',{name:'Download build summary'}).click();const dl=await d;const text=fs.readFileSync(await dl.path(),'utf8');assert(text.includes('$7,965'));assert(text.includes('1-year limited'));await page.locator('#editBuild').click();
 await page.locator('#budget').selectOption('1000');assert((await page.locator('#liveSummary .price').textContent()).includes('924'));
 await page.goto(base+'support.html?topic=warranty');assert.equal(await page.locator('#topic').inputValue(),'Warranty question');await page.locator('#name').fill('Test User');await page.locator('#email').fill('test@example.com');await page.locator('#message').fill('Test only.');const request=page.waitForEvent('download');await page.getByRole('button',{name:'Download request'}).click();await request;
 for(const size of [{width:375,height:812},{width:812,height:375}]){await page.setViewportSize(size);for(const file of paths){await page.goto(base+file);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),file+' mobile overflow');}await page.locator('#menuToggle').click();assert(await page.locator('#navLinks').isVisible());await page.getByRole('navigation').getByRole('link',{name:'Custom Build',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#buildViewport').dataset.modelRevision);assert(await page.locator('#buildViewport canvas').isVisible());}
 fs.mkdirSync(path.join(__dirname,'../test-results'),{recursive:true});await page.setViewportSize({width:1440,height:1050});await page.goto(base+'custom-build.html?base=max');await page.waitForFunction(()=>document.querySelector('#buildViewport').dataset.camera);await page.screenshot({path:'test-results/max-desktop.png',fullPage:true});await page.locator('[data-preset=maxed]').click();await page.locator('#buildViewport').screenshot({path:'test-results/viewer.png'});await page.setViewportSize({width:375,height:812});await page.screenshot({path:'test-results/max-mobile.png',fullPage:true});
 const noGL=await browser.newPage();await noGL.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type.startsWith('webgl')?null:original.call(this,type,...args);};});await noGL.goto(base+'custom-build.html');assert((await noGL.locator('#previewStatus').textContent()).includes('unavailable'));assert(await noGL.locator('#reviewBuild').isEnabled());await noGL.close();
 await page.goto('file://'+path.resolve(__dirname,'../custom-build.html')+'?base=max');await page.waitForFunction(()=>document.querySelector('#buildViewport').dataset.modelRevision);assert(await page.locator('#reviewBuild').isEnabled());assert.deepEqual(errors,[]);console.log('PASS: 13 entry points, internal links, four tiers, $4,000/$7,965 MAX, catalog counts, platform/PSU/case/cooling/RAM checks, live 3D updates and controls, review/downloads, warranty, desktop/mobile/landscape, no-WebGL fallback, file:// mode; no JS errors.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.kill());
