"""Import curated models from a pinned, MIT-licensed public catalog (not live stock).
Run: python3 scripts/sync_catalog.py
Keep selectors and compatibility metadata under review when changing SOURCE_REV.
"""
from pathlib import Path
import json, subprocess
ROOT=Path(__file__).resolve().parent.parent
SOURCE_REV='c52a04ca9465c83997ed335f7767b09a2005dd26'
BASE=f'https://raw.githubusercontent.com/docyx/pc-part-dataset/{SOURCE_REV}'
def fetch(path):
 return subprocess.check_output(['curl','--fail','--location','--silent','--show-error','--max-time','40',BASE+'/'+path]).decode()
def pick(rows, **fields):
 for r in rows:
  if all(r.get(k)==v for k,v in fields.items()) and isinstance(r.get('price'),(int,float)) and r['price']>0:return r
 raise ValueError(f'Missing priced source row: {fields}')
def entry(name,row,**meta):return [name,round(row['price']),dict(meta,source=row)]
cpu_rows=json.loads(fetch('data/json/cpu.json'))
gpu_rows=json.loads(fetch('data/json/video-card.json'))
ram_rows=json.loads(fetch('data/json/memory.json'))
cpu_names=['AMD Ryzen 5 7600','AMD Ryzen 7 7700','AMD Ryzen 7 7800X3D','AMD Ryzen 5 9600X','AMD Ryzen 7 9700X','AMD Ryzen 7 9800X3D','AMD Ryzen 9 9900X','AMD Ryzen 9 9950X','AMD Ryzen 9 9950X3D','Intel Core i5-14400F','Intel Core i5-14600K','Intel Core i7-14700K','Intel Core i9-14900K','Intel Core Ultra 5 245K','Intel Core Ultra 7 265K','Intel Core Ultra 9 285K']
cpus=[]
for i,name in enumerate(cpu_names):
 row=pick(cpu_rows,name=name)
 socket='AM5' if i<9 else 'LGA1700' if i<13 else 'LGA1851'
 cooling=0 if i in [0,1,3,4,9] else 1 if i in [2,5,6,10,13] else 2
 cpus.append(entry(name,row,brand=name.split()[0],socket=socket,minCooling=cooling,score=[.86,.94,1,.95,1.02,1.12,1.02,1.08,1.15,.82,.94,1,1.02,.92,.99,1.05][i],maxMemory=192 if i in [7,8,12,14,15] else 128))
# Minimum PSU values are conservative Vertex configuration rules, not manufacturer claims.
gpu_specs=[
 ('Asus DUAL OC V2','GeForce RTX 4060',8,650,.4),
 ('Gigabyte WINDFORCE OC','GeForce RTX 4070 SUPER',12,750,.7),
 ('Gigabyte WINDFORCE V2','GeForce RTX 4080 SUPER',16,850,1),
 ('Asus PRIME','GeForce RTX 5060 Ti',16,650,.55),
 ('MSI VENTUS 2X PLUS OC','GeForce RTX 5060 Ti',16,650,.55),
 ('Gigabyte WINDFORCE OC SFF','GeForce RTX 5070',12,750,.8),
 ('PNY OC','GeForce RTX 5070',12,750,.8),
 ('MSI VENTUS 3X OC','GeForce RTX 5070 Ti',16,850,1.02),
 ('Asus TUF GAMING OC','GeForce RTX 5080',16,1000,1.2),
 ('Asus ROG Astral OC','GeForce RTX 5080',16,1000,1.2),
 ('Asus ROG Astral OC','GeForce RTX 5090',32,1000,1.65),
 ('Gigabyte AORUS MASTER','GeForce RTX 5090',32,1000,1.65),
 ('Asus DUAL EVO OC','Radeon RX 7600',8,650,.39),
 ('XFX Speedster QICK 319 Core','Radeon RX 7800 XT',16,750,.65),
 ('Sapphire PULSE','Radeon RX 9070 XT',16,850,.96),
 ('Gigabyte GAMING OC','Radeon RX 9070 XT',16,850,.96),
 ('Intel Limited Edition','Arc B580',12,650,.43),
 ('Sparkle TITAN OC','Arc B580',12,650,.43)]
gpus=[]
for name,chip,memory,psu,score in gpu_specs:
 row=pick(gpu_rows,name=name,chipset=chip,memory=memory)
 gpus.append(entry(f'{name} · {chip} {memory}GB',row,brand=name.split()[0],chipset=chip,minPsu=psu,score=score,length=row['length'],fans=2 if row['length']<285 else 3,color='white' if row.get('color')=='White' else 'black'))
ram_specs=[('Kingston FURY Beast 16 GB',[2,8],5200),('Corsair Vengeance RGB 32 GB',[2,16],6000),('G.Skill Trident Z5 RGB 64 GB',[2,32],6400),('G.Skill Flare X5 32 GB',[2,16],6000),('Kingston FURY Beast 32 GB',[2,16],6000),('Crucial Pro Overclocking 32 GB',[2,16],6000),('TEAMGROUP T-Create Expert 32 GB',[2,16],6000),('TEAMGROUP T-Force Delta RGB 32 GB',[2,16],6000),('Patriot Viper Venom 32 GB',[2,16],6000),('Corsair Vengeance RGB 192 GB',[4,48],5200)]
rams=[]
for name,modules,speed in ram_specs:
 row=pick(ram_rows,name=name,modules=modules,speed=[5,speed])
 rams.append(entry(f'{name} · {modules[0]} × {modules[1]}GB DDR5-{speed} CL{row["cas_latency"]}',row,brand=name.split()[0],capacity=modules[0]*modules[1],sticks=modules[0],rgb='RGB' in name,color='white' if row.get('color')=='White' else 'black'))
output=dict(source='https://github.com/docyx/pc-part-dataset',revision=SOURCE_REV,sourceUpdated='2025-07-23',pricing='Historical catalog prices, rounded to USD estimates. Not current offers or stock.',cpu=cpus,gpu=gpus,memory=rams)
(ROOT/'assets/catalog/parts.json').write_text(json.dumps(output,indent=2)+'\n')
(ROOT/'assets/catalog/parts.js').write_text('/* Generated by scripts/sync_catalog.py. See catalog source and license. */\nwindow.VertexImported = '+json.dumps(output,separators=(',',':'))+';\n')
(ROOT/'assets/catalog/LICENSE.txt').write_text(fetch('LICENSE'))
print(f'Imported {len(cpus)} CPUs, {len(gpus)} GPUs, {len(rams)} DDR5 kits from {SOURCE_REV}.')
